services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER : run/secrets/db_password
      POSTGRES_PASSWORD : root
      POSTGRES_DB=root : root
      # - POSTGRES_USER=root
      # - POSTGRES_PASSWORD=root
      # - POSTGRES_DB=root
    secrets:
      - db_password
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    image: golang:1.22
    command:
      - go
      - run
      - main.go
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=root
      - DB_PORT=5432

secrets:
   db_password:
     file: .secrets/db_password.txt
