name: Continuos Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.17"

      - name: Start database
        run: docker compose up -d postgres
      
      - name: Lint
        ## Remove run when I uncomment the correction for the pipeline
        run: docker run --rm -itv $(CURDIR):/app -w /app golangci-lint golangci-lint run controllers/ database/ models/ routes/
        # uses: golangci/golangci-lint-actions@v6
        # with:
        #   version: "v1.59"
        ## Inform which foldes I wanna run the lint
        #   args: controllers/ database/ models/ routes/
        # Aula 03 - Executando na esteira

      # - name: Test
      #   run: DB_HOST=${{ secrets.DB_HOST }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_USER=${{ secrets.DB_USER }} DB_NAME=${{ secrets.DB_NAME }} DB_PORT=${{ secrets.DB_PORT }} go test -v main_test.go
